## Spring Boot App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      name: trialpod
      labels:
        app: trial
    spec:
      containers:
      - name: trialcontainer
        image: indium01/trial-latest:v2
        imagePullPolicy: always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: trial
spec:
  selector:
    app: trial
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
